### PR TITLE
fix: remove default custom serialization and make it an opt-in option

### LINKED ISSUE #261: Make sure the store serialization follows redux recommendations
> Actually I don't like idea of having this by default baked into the lib - it goes kinda against the redux recommendations itself:
> 
> It is highly recommended that you only put plain serializable objects, arrays, and primitives into your store.
> 
> I would like to extract this and make it configurable so users when using the middleware can configure it with their own serializer at their own risk (and we ofc can provide them with example serializer used here 👍🏻 )

As a follow up we should address this on v2

### PR DESCRIPTION
**Pull request by matmalkowski**
Removing custom serializer as a default, since its not alligned with redux recommendation about store
& serialization
You can still opt-in for some custom functions via options when creating the enhancers.

Renamed the main functions too.

fix #261

### CODE REVIEW

File: src/rendererStateSyncEnhancer.ts [hunk 1]
```diff
@@ -1,19 +1,24 @@
 import { ipcRenderer } from 'electron'
 import { Action, applyMiddleware, Middleware, Reducer, StoreCreator, StoreEnhancer } from 'redux'
 
-import { hydrate, preventDoubleInitialization, stopForwarding, validateAction } from './utils'
+import { preventDoubleInitialization, stopForwarding, validateAction } from './utils'
 
-async function getRendererState(callback: (state: unknown) => void) {
+async function fetchInitialState(
```
Comment (victorhqc) [inline src/rendererStateSyncEnhancer.ts:6]: Nice naming

File: src/mainStateSyncEnhancer.ts [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+}
+
+const defaultOptions: MainStateSyncEnhancerOptions = {}
+
+/**
+ * Creates new instance of main process redux enhancer.
+ * @param {MainStateSyncEnhancerOptions} options Additional enhancer options
+ * @returns StoreEnhancer
+ */
+export const mainStateSyncEnhancer = (options = defaultOptions): StoreEnhancer => (
```
Comment (victorhqc) [inline src/mainStateSyncEnhancer.ts:56]: 👍

**Review by victorhqc — APPROVED** [review]
looking good!
